### ISSUE TITLE
Improper font scaling

### ISSUE THREAD

**Issue by Detenog** [Hypnootize/PV-Hud#1]
The font is bigger in a 1600x900 (16:9), but in 1920x1080 (16:9) the font is smaller.

Screenshots:
1600x900: https://steamcommunity.com/id/Detenog/screenshot/777351870681650197

1920x1080: https://steamcommunity.com/id/Detenog/screenshot/777351870681651286

**Comment by Detenog** [comment]
Hello?

**Comment by Hypnootize** [comment]
Thats just how resolution scaling works it happens with every hud. I can't make 20+ adaptations to make it the same size for every single resolution out there.

You can still look for "HudFontHUGE" inside the clientscheme and reduce his tall when you play on smaller resolutions.

**Comment by Detenog** [comment]
Thanks!
